# These are supported funding model platforms

github: [raimannma] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: user?u=68961896 # Replace with a single Patreon username
